version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: userAuth-api
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: securityGi
      POSTGRES_USER: useroauth
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: